feat: добавить контроллеры для User и Item
RuslanBoo/java-shareit pull request #1
Opened 2023-01-11 11:25 UTC by RuslanBoo

2023-01-12 07:39 UTC, AnastasiyaFomkina requested changes
Отличная работа - молодец 👍

2023-01-12 07:39 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/error/ErrorHandler.java
> +    public ErrorResponse handleBadRequestException(final BadRequestException e) {
Лучше переименовать все однобуквенные переменные

2023-01-12 07:39 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +    public ItemDto toDto(Item item) {
_Саморазвитие_
В коммерческой разработке принято максимально избавляться от шаблонного кода, чтобы не перегружать и так большие и объемные проекты. Для маппинга сущностей часто используется библиотека [Mapstruct](https://blog.skillfactory.ru/glossary/mapstruct/), которая позволяет автоматически настраивать маппинг из одной сущности в другую с помощью описания интерфейсов и аннотаций.
Вот [здесь](https://www.baeldung.com/mapstruct) есть отличный гайд для старта работы с библиотекой.
При наличии свободного времени можно поизучать и попробовать прикрутить в проект

2023-01-12 07:39 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>   */
В коммерческой разработке, когда код из `TODO` реализован, принято его удалять, чтобы он не путал других разработчиков.
Удали, пожалуйста, все `TODO`, которые были выполнены во всем проекте

2023-01-12 07:39 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public List<ItemDto> getByOwner(@RequestHeader(value = "X-Sharer-User-Id") long ownerId) {
Можно вынести повторяющийся хэдер в константу

2023-01-12 07:39 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/service/InMemoryItemService.java
> +            if (itemDto.getAvailable() == null) {
Вместо множественных проверок, лучше использовать [аннотации валидации](https://reflectoring.io/bean-validation-with-spring-boot/#:~:text=certain%20annotations.-,Common%20Validation%20Annotations,-Some%20of%20the) над полями DTO объектов, как для предметов, так и для пользователей

2023-01-12 16:53 UTC, RuslanBoo commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +    public ItemDto toDto(Item item) {
@AnastasiyaFomkina Отлично, прикрутил, большое спасибо!  🔥

Раз уж зашла речь про оптимизацию, не могла бы подсказать по поводу метода partialUpdate - мне кажется должно быть какое то готовое решение для изменения только некоторых передаваемых полей, но нагуглить не смог нормальной реализации из коробки

2023-01-13 13:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +    public ItemDto toDto(Item item) {
Можно обрабатывать такие моменты с помощью mapstruct. Тут придется добавить чуть больше настроек для маппера и покопаться в библиотеке. Вот отличный [гайд](https://kdrozd.pl/how-to-perform-a-partial-update-patch-with-explicit-null/) через `JsonNullable`. Я на прошлом проекте писала через `Optional`, но подобный гайд найти не могу :(

2023-01-13 13:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +    public ItemDto toDto(Item item) {
Но как правильно говорится в статье, смысл  и решение примерно одинаковое

2023-01-13 13:53 UTC, AnastasiyaFomkina requested changes
Молодец, что изучил mapstruct 👍 Оставила один комментарий, и пояснение к particial update, если будет желание и время, можно попробовать реализовать

2023-01-13 13:53 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/UserMapper.java
> +    @Mapping(target = "email", source = "email")
Если поля в двух сущностях имеют одинаковые названия, то можно опустить данную аннотацию, `mapstruct` самостоятельно поймет из какого поля в какое перекладывать значение.
Предлагаю удалить все `@Mapping` по проекту

2023-01-14 18:08 UTC, RuslanBoo commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +    public ItemDto toDto(Item item) {
@AnastasiyaFomkina Спасибо большое! Настроил - это просто пушка-гонка! То что нужно 🔥🔥🔥

2023-01-14 18:10 UTC, RuslanBoo commented on src/main/java/ru/practicum/shareit/user/UserMapper.java
> +    @Mapping(target = "email", source = "email")
удалил, но оставил в двух местах ignore так как id из DTO не тянутся, а берутся из PathVariable

2023-01-15 14:37 UTC, AnastasiyaFomkina approved these changes

2023-01-16 13:27 UTC, merged