feat: add item requests
RuslanBoo/java-shareit pull request #5
Opened 2023-03-22 17:59 UTC by RuslanBoo

add item requests

2023-03-23 12:21 UTC, afomkina requested changes
Привет! Ты проделал огромную работу - молодец 🔥
Оставила много небольших комментариев, не пугайся, все очень легко поправить.
В целом нужно обратить внимание на то, чтобы максимально избавляться от дублирований - чем больше одинакового кода, тем сложнее его читать и поддерживать. Постарайся, также не подключать объекты, которые не будут использоваться в тестах, они занимают место в памяти приложения и в коде.
Ну и еще немного: если будет время, можно еще чуть-чуть улучшить читаемость тестов, если использовать [@Nested](https://www.petrikainulainen.net/programming/testing/junit-5-tutorial-writing-nested-tests/). С помощью данной аннотации можно побить тесты на логические блоки, таким образом их будет проще воспринимать визуально, соответственно - проще поддерживать

2023-03-23 12:21 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +@Service
Не нужно делать этот интерфейс бином, так как класс, которые уже является бином

2023-03-23 12:21 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    @Autowired
Уже есть `@RequiredArgsConstructor`, он автоматически инжектит все поля с модификатором `final` в конструторе

2023-03-23 12:21 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    private final PaginationService paginationService;
Нигде не используется, нужно удалить

2023-03-23 12:21 UTC, afomkina commented on src/main/java/ru/practicum/shareit/item/model/Item.java
Лучше отказаться от использования @Data в сущностях jpa, так как это приводит к [вот этой проблеме](https://habr.com/ru/company/haulmont/blog/564682/)

2023-03-23 12:21 UTC, afomkina commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
>  @Data
Лучше удалить `@Data`опираясь на комментарий выше

2023-03-23 12:21 UTC, afomkina commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
>   * TODO Sprint add-item-requests.
Забыл удалить `TODO`

2023-03-23 12:21 UTC, afomkina commented on src/main/java/ru/practicum/shareit/request/repository/ItemRequestRepository.java
> +    public List<ItemRequest> findAllByRequestorIdOrderByCreatedDesc(long requestorId);
Метод не используется, лучше его удалить

2023-03-23 12:21 UTC, afomkina commented on src/main/java/ru/practicum/shareit/request/repository/ItemRequestRepository.java
> +    public List<ItemRequest> findAllByRequestorIdOrderByCreatedDesc(long requestorId, Pageable pageable);
Все методы интерфейс по умолчанию `public`, лучше удалить ненужный модификатор доступа. Проверь, пожалуйста, что его нет и в других интерфейсах

2023-03-23 12:21 UTC, afomkina commented on src/main/java/ru/practicum/shareit/request/repository/ItemRequestRepository.java
> +    public List<ItemRequest> findAllByRequestorIdIsNotOrderByCreatedDesc(long requestorId);
Метод не используется, лучше его удалить

2023-03-23 12:21 UTC, afomkina commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +@AllArgsConstructor
Лучше поставить более узкий `@RequiredArgsConstructor`, так как мы хотим ижектить только определенные поля, а не все поля класса

2023-03-23 12:21 UTC, afomkina commented on src/test/java/ru/practicum/shareit/booking/enums/BookingPermissionTest.java
> +class BookingPermissionTest {
Тесты энамов походи на тесты ради покрытия. Их нужно дописать или удалить и проверять реальную функциональность в других местах. Например, при тестировании сервиса, где они реально использутся

2023-03-23 12:21 UTC, afomkina commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    private Helper helper = new Helper();
Не используется, нужно удалить

2023-03-23 12:21 UTC, afomkina commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +                        .header("X-Sharer-User-Id", String.valueOf(userId))
Лучше вынести публичной константой в отдельный класс и переиспользовать по всему приложению, чтобы не дублировать каждый раз строку. Это очень поможет в случае, если хэдер решит измениться, тогда не придется править кучу классов, а нужно будет изменить строку только в одном месте

2023-03-23 12:21 UTC, afomkina commented on src/test/java/ru/practicum/shareit/booking/BookingMapperImplTest.java
> +class BookingMapperImplTest {
Опять же тесты ради покрытия. Так не пойдет, нужно написать реальные :)

2023-03-23 12:21 UTC, afomkina commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +    private Mock mock;
Не используется, нужно удалить

2023-03-23 12:21 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +        Booking booking = Helper.createBokking(bookingId, item, user);
Очень много повторяющегося кода. Например, строки 86-93 повторяются в тестах ниже несколько раз. Можно очень сильно оптимизировать код, если вынести подобные моменты в `BeforeEach` или отдельный приватный метод

2023-03-23 12:21 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +    private CommentMapper commentMapper = Mappers.getMapper(CommentMapper.class);
Лишний, нужно удалить

2023-03-23 12:21 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/comment/CommentMapperTest.java
> +    private Mock mock;
Лишний, нужно удалить

2023-03-23 12:21 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/comment/CommentMapperTest.java
> +        User user = Helper.createUser(userId);
Все перднастроки лучше вынести в BeforeEach или отдельный метод

2023-03-23 12:21 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/error/ErrorHandlerTest.java
> +    private Mock mock;
Лишний, нужно удалить

2023-03-23 12:21 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/error/ErrorHandlerTest.java
> +    private ErrorHandler errorHandler = new ErrorHandler();
Лучше сделать `final`

2023-03-23 12:21 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +    private Helper helper = new Helper();
Удали, пожалуйста, во всех тестах лишние helper'ы, mock'и и spy мапперов, которые не используются

2023-03-23 12:21 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/pagination/PaginationServiceTest.java
> +    PaginationService paginationService = new PaginationService();
Не хватает модификатора доступа

2023-03-23 12:21 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/pagination/PaginationServiceTest.java
> +@ExtendWith(MockitoExtension.class)
Не нужен, так как ничего не мокаем

2023-03-23 12:21 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/user/UserControllerTest.java
> +    private Helper helper = new Helper();
Все методы класса Helper статичекие, для доступа к статическим методом не нужно создавать объект. Вот [здесь](https://vertex-academy.com/tutorials/ru/modifikator-static-v-java-metody/) можно вспомнить про модификатор static

2023-03-23 20:19 UTC, RuslanBoo commented
> Привет! Ты проделал огромную работу - молодец 🔥 Оставила много небольших комментариев, не пугайся, все очень легко поправить. В целом нужно обратить внимание на то, чтобы максимально избавляться от дублирований - чем больше одинакового кода, тем сложнее его читать и поддерживать. Постарайся, также не подключать объекты, которые не будут использоваться в тестах, они занимают место в памяти приложения и в коде. Ну и еще немного: если будет время, можно еще чуть-чуть улучшить читаемость тестов, если использовать [@Nested](https://www.petrikainulainen.net/programming/testing/junit-5-tutorial-writing-nested-tests/). С помощью данной аннотации можно побить тесты на логические блоки, таким образом их будет проще воспринимать визуально, соответственно - проще поддерживать

Большое спасибо за nested, обязательно разберусь - жаль не знал об этом до начала написания тестов. Сейчас к сожалению не успею, и так пришлось академ взять чтобы успеть. Поправил все моменты, в некоторых местах оставил spy для mapper - они светятся серым т.к. нет прямого обращения, но без них в классах на тестах сыпется NullPointerException. С Возвращением! А то уже переживать начал что ревьер сменился - и стало слишком легко 🥳👏🏻

2023-03-24 15:28 UTC, AnastasiyaFomkina requested changes
Нужно избавиться от дублирований в тестах. Все преднастройки можно вынести в `@BeforeEach`, а повторяющиеся части проверок в отдельные приватные методы. Чуть выше были примеры, что конкретно считается дублированием :)

2023-03-24 15:28 UTC, afomkina commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +@EqualsAndHashCode
Лучше пока тоже удалить у всех сущностей, так как в курсе не разбиралось, как корректно генерить `equals` и `hashcode` с `jpa`. Вообще у `jpa` есть множество проблем, поэтому в больших и сложных проектах чаще всего используют jdbc. [Вот](https://habr.com/ru/company/otus/blog/529692/), например, одна из самых серьезных

2023-03-24 15:28 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +                        .header("X-Sharer-User-Id", String.valueOf(userId))
Нужно вынести в отдельный класс и сделать публичной константой. После подменить все использования по проекту на константу. Это очень легко сделать сочетанием клавиш ctrl+r

2023-03-28 07:39 UTC, AnastasiyaFomkina approved these changes

2023-03-29 16:23 UTC, merged